# Site
repository: sudoitir/cv
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Mahdi Amirabdolahi
title: Java Developer
email: mahdi.amirabdolahi@gmail.com
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username: sudoitir
stackoverflow_username: "17410589"
linkedin_username: mahdiamirabdolahi

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
#about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  As a driven and dedicated Java developer with over a year of experience in the industry, I am committed to creating |
  innovative and high-performing software solutions. My expertise lies in developing and maintaining Java-based web |
  applications, as well as working with various frameworks such as Spring and Hibernate.
  I am passionate about software development, and I believe that my technical skills and problem-solving abilities |
  will enable me to contribute to the success of any project. I am always open to new challenges and am always looking |
  to improve my skills and knowledge.
  
  If you are looking for a motivated and results-driven Java developer, I would love to connect with you on LinkedIn, |
  and explore any potential opportunities or projects that you may have.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Rayan Bourse
        sub_title: Java Developer
        caption: Jan 2023 - present
        link: https://www.linkedin.com/company/rayan-bourse
        quote: >
          A software developer and service provider company in Iran's capital market.
        description: | # this will include new lines to allow paragraphs
          Description of role
      - layout: left
        title: Negah Bank
        sub_title: Java Developer
        caption: Sep 2022 - Jan 2023
        link: https://www.linkedin.com/company/negah-bank/
        quote: >
          Banking technologies products and services.
        description: | # this will include new lines to allow paragraphs
          In my time at Negah Bank, I was responsible for developing, and maintaining web-based applications using Java |
          technologies. I worked closely with a team of developers and stakeholders to deliver high-quality software |
          solutions that met the needs of the business. My skills in web development technologies and frameworks |
          such as Spring and Hibernate, as well as my experience with Agile development methodologies, enabled me to |
          make meaningful contributions to the team.
      - layout: left
        title: HAYTech
        sub_title: Junior Java Developer
        caption: Jan 2022 - Sep 2023
        link: https://www.haytech.ir/en/
        quote: >
          Startup company.
        description: | # this will include new lines to allow paragraphs
          At the start of my career, I gained valuable experience in both development and deployment while working for |
          a startup. Specifically, I played an instrumental role in the development and deployment of a project aimed |
          at automating social media responses. This experience allowed me to hone my skills as a backend developer and |
          taught me valuable lessons about project management and teamwork.
          I worked on:Spring Boot project based on clean architecture, I used these technologies: Spring AOP,|
          Spring Data JPA, Spring Security, Map Struct, Lombok , JUnit 5, Mockito  Dockerize the project |
          Gitlab Ci (Running unit tests, checking security and code quality)



  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
        # other value (or no value) means no border will be displayed
        title: HSE
        quote: >
          (Environment - health - safety)
        description: | # this will include new lines to allow paragraphs
          HSE project for Pars Petrochemical Co.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Personal Development Process
        sub_title: Java Backend Developer
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
